name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        IMAGE_TAG: kazuyamamoto/alpine-ca-cert:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ IMAGE_TAG }}
    - name: Login Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push the Docker image
      run: docker push ${{ IMAGE_TAG }}
